### ISSUE TITLE
Ch10 실행계획 나누어서 진행

### ISSUE THREAD

**Issue by ghojeong** [BackendSquid/RealMySQL#19]
@jihye-woo @ghojeong 

10.3.12 Extra 칼럼 이전까지 woody 가 진행
이후는 Pyro 가 진행

**Comment by kihyuk-sung** [comment]
10.2 까지는 간단히 읽기.
10.3 부터 실행계획 분석이라 중요한 내용

**Comment by jihye-woo** [comment]
아 파이로까지 하고서 닫았어야 했던 것 같기도 하구요...? 다시 리오픈 합니다ㅎㅎ;;

**Comment by ghojeong** [comment]
제것까지 끝냈으니 Close 합니다.
