### ISSUE TITLE
Ch11. 쿼리 작성 및 최적화 - 1

### ISSUE THREAD

**Issue by ghojeong** [BackendSquid/RealMySQL#23]
p.64

WHERE 조건과 ORDER BY 절, GROUP BY 절의 인덱스 사용까지!

서기: K

**Comment by janeljs** [comment]
- 기존 버전에서 sql_mode 설정 안하다가 8.0으로 버전업하면 ONLY_FULL_GROUP_BY 옵션에 주의해야 하는 이유?
  - group by 절이 사용된 문장의 select 절에는 group by 절에 명시된 컬럼과 집계함수(count, sum)만 사용 가능하도록 강제하는 옵션
  - 5.7까지는 기본값으로 비활성화되었었는데 8.0부터 활성화되었기 때문
- lower_case_table_names 설정하면 테이블 대소문자를 운영체제 종속적이지 않게 사용 가능
- 테이블 생성시 (`)으로 감싸지 않고 생성해보기
- VALUES(col_name)
  - https://tomining.tistory.com/198
  - https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html
- tinyint
  - https://heavening.tistory.com/85
 - p.11 true는 c언어와 달리 1만을 의미한다는 것의 의미?
   - mysql은 c/c++언어에서처럼 TRUE, FALSE 같은 불리언 값을 정수로 매핑해서 사용하는 것
   - C언어에서 거짓(false)은 0이며, 0이 아닌 모든 것은 참(true)으로 인식
   - http://www.tcpschool.com/c/c_operator_logic
   - https://dojang.io/mod/page/view.php?id=745
- 불리언 타입을 꼭 사용하고 싶다면 enum 타입으로 관리하는 것이 더 좋은 이유?
  - 'Y', 'N'?
  - https://stackoverflow.com/questions/4180956/enum-or-bool-in-mysql
- 인덱스 앞쪽에 있는 컬럼의 selectivity가 떨어지면 in으로 변경해서 성능 개선 가능
- key_len
  - 쿼리를 처리하기 위해 다중 칼럼으로 구성된 인덱스에서 몇개의 칼럼까지 사용했는지
  - string을 인덱스로 넣을때는 조심해야 한다.
  - utf8mb4
  - https://weicomes.tistory.com/151
  - https://stackoverflow.com/questions/7643491/understanding-mysql-key-len-in-explain-statement
- replica 구성시 sysdate-is-now 설정해두면 쿼리 실행 시간과 관계없이 같은 값 보장 가능
- 성능테스트용으로 좋은 함수 - benchmark, sleep
   - 그러나 쿼리를 직접 실행하는 것과는 다른게 네트워크, 쿼리 파싱 및 최적화 비용이 1번만 수행되기 때문임
- view vs inline view
  - https://wikidocs.net/147055
- 이전 챕터에서 나왔지만 중요한 내용들
  - 인덱스 건 컬럼값에 연산 등 변형이 들어가면 인덱스 못탐
  - 이럴땐 Virtual Column 추가하고 그 컬럼에 인덱스 걸어서 사용하면 됨
  - where 조건에 or 연산자 있으면 옵티마이저가 풀 테이블 스캔 사용함 
- 시간
  - https://velog.io/@dion/mysql-5-7-datetime
  - https://nesoy.github.io/articles/2020-02/mysql-datetime-timestamp
  - https://codingdog.tistory.com/entry/mysql-timestamp%EB%8A%94-datetime%EA%B3%BC-%EB%B9%84%EA%B5%90%ED%96%88%EC%9D%84-%EB%95%8C-%EB%AC%B4%EC%97%87%EC%9D%B4-%EB%8B%A4%EB%A5%BC%EA%B9%8C%EC%9A%94
  - date
  - time
  - datetime
  - timestamp
- 쿼리에도 short-circuit evaluation이 적용된다. But, where 절 조건 중에 인덱스 사용하는 조건이 있다면 그게 최우선으로 적용된다. 
   - 복잡한 연산 서브쿼리 조건 등은 where 절의 뒤쪽으로 배치하는 것이 성능상 유리할 것이다.

**Comment by sanhee** [comment]
- 불리언 (10p)
  - BOOL이나 BOOLEAN 타입은 TINYINT 타입에 대한 동의어
- GROUP BY 문자열 결합 (GROUP_CONCAT) (32p)
  - GROUP_CONCAT() 함수는 지정한 칼럼의 값들을 연결하기 위해 제한적인 메모리 버퍼 공간을 사용
  - JDBC로 실행될 때 시스템 변수에 지정된 버퍼 크기를 초과하면 에러로 취급하므로 주의 해야 함.
- MySQL 8.0 이전 버전까지는 GROUP BY의 그룹별로 개수를 제한해서 가져올 수 있는 방법이 없음. (34p)
  - MySQL 8.0 부터는 용도에 맞게 `레터럴 조인`이나 `윈도우 함수`를 이용할 수 있음. 
- BENCHMARK() 함수 : 디버깅이나 함수의 성능 테스트용 (43p)
  - 벤치마크 함수는 1번의 네트워크 비용, 최적화 비용이 소모되어 쿼리를 직접 실행하는 것과는 차이가 있음
  - 두 개의 동일 기능을 상대적으로 비교 분석하는 용도 
  
- REGEXP, LIKE 연산자 (17p)
  - REGEXP 조건의 비교는 인덱스 레인지 스캔을 사용할 수 없다.
  - LIKE 연산자는 와일드카드 문자(%, _)가 검색어의 **뒤쪽**에 있다면 인덱스 레인지 스캔으로 사용할 수 있다.
- BETWEEN 연산자로 다른 비교 조건과 결합해 하나의 인덱스를 사용할 때 주의할 점 (19p)
  - 범위를 읽어야 하는 연산자라 모든 인덱스 범위를 검색해야 함
  - 여러 컬럼으로 인덱스가 만들어져 있는데, 인덱스 앞쪽에 있는 칼럼의 선택도가 떨어질 때는 IN으로 변경하는 방법으로 쿼리 성능을 개선할 수도 있음.
  
- 인덱스를 사용하기 위한 기본 규칙 (55p)
  - 기본적으로 인덱스 된 칼럼의 값 자체를 변환하지 않고 그대로 사용한다는 조건을 만족해야 한다. 
    - ex) 날짜 칼럼을 문자열로 변경하거나 더하거나 빼는 함수로 변형하면 인덱스를 효율적으로 이용하지 못함. (69p)  
   
- WHERE 절의 비교 조건 사용 시  주의 사항 (9p, 56p, 58p, 66p)
   - 두 칼럼 중 하나의 칼럼만 인덱스가 있는 상황에서 OR 연산자가 있으면 옵티마이저는 풀 테이블 스캔을 선택한다.
     - 이유: `(풀 테이블 스캔)` 작업량  < `(풀 테이블 스캔) + (인덱스 레인지 스캔)`의 작업량 
   - 문자열 칼럼이나 숫자 칼럼을 비교할 때는 반드시 그 타입에 맞는 상수 값 사용
      - MySQL은 숫자 타입과 문자 타입 간의 비교에서 숫자 타입을 우선 시함. 
      - 타입이 서로 다를 경우, 옵티마이저가 내부적으로 문자열 타입을 숫자 타입으로 변환한 후 비교 작업을 처리한다. 
      - 따라서, 칼럼의 모든 값이 숫자로 캐스팅 돼서, 인덱스를 이용하지 못하는 경우가 생길 수 있으므로 주의
   - NULL 비교, ISNULL() 함수를 WHERE 조건에서 사용할 때 주의 할 점
    ```sql
    mysql> SELECT * FROM titles WHERE to_date IS NULL;   // 인덱스 레인지 스캔
    mysql> SELECT * FROM titles WHERE ISNULL(to_date);   // 인덱스 레인지 스캔
    mysql> SELECT * FROM titles WHERE ISNULL(to_date)=1;   // 인덱스 풀 스캔
    mysql> SELECT * FROM titles WHERE ISNULL(to_date)=true;   // 인덱스 풀 스캔
    ```
     
- DISTINCT
https://github.com/BackendSquid/RealMySQL/blob/main/Ch09.md#:~:text=9.2.5-,DISTINCT%20%EC%B2%98%EB%A6%AC,-DISTINCT%EB%8A%94%20%EC%A7%91%EA%B3%84%ED%95%A8%EC%88%98%EC%9D%98

**Comment by kihyuk-sung** [comment]
## 11. 2 매뉴얼의 sql 문법 표기 읽는 법
- BNF 표기법 
- https://ko.wikipedia.org/wiki/%EB%B0%B0%EC%BB%A4%EC%8A%A4-%EB%82%98%EC%9A%B0%EB%A5%B4_%ED%91%9C%EA%B8%B0%EB%B2%95
## 11.3.2.4 AND와 OR 연산자
- OR 연산자의 경우 조심해서 써야 함
- 잘못하면 index를 타지 않음
ex) where category_id is null or categori_id = 3 (O, ref_or_null)
where created_at < T1 or created_at = T1 and id not in (1, 2, 3) (x)
## 11.3.2.6 REGEXP
- index를 타지 않으므로 범위를 좁히는 조건과 같이 사용하기
## 11.3.3.15 IP 주소 변환
- ipv6 는 16바이트 (128비트) ipv4 는 4바이트(32비트) 로 저장할 수 있음
- 이를 변환하는 함수를 mysql에서 제공
## 11.4 SELECT
- LIMIT 가 일반적으로 제일 마지막에 처리됨
- 그러므로, using file-sort 등의 작업이 존재하는 경우 limit 가 조회 범위를 줄여주지 못할 가능성이 큼

**Comment by kyupid** [comment]
11.3.1.1 문자열
- Q) 굳이 따옴표로 나눠서 쓰는 이유도 있으니까 이런 표현법이 있는거겠지?

11.3.2.6 REGEXP 연산자
- 정규표현식도 사용할수 있는건 첨 알았다

11.3.2.7 LIKE 연산자
- 'Christ%' VS '%rist' ->  왼쪽꺼만 인덱스 레인지 스캔 이용가능
- 오른쪽은 인덱스의 Left-most 특성으로 인해 풀스캔

11.3.2.8 BETWEEN 연산자
- SELECT * FROM dept_emp WHERE dept_no='d003' AND emp_no=10001;
- SELECT * FROM dept_emp BETWEEN 'd003' AND 'd005' AND emp_no=10001;
- 두 쿼리의 인덱싱 방법은 다르다
- BETWEEN 사용한건 범위에 있는걸 다 가져오기 때문에 AND 가 무시된다
- 저렇게하려면 IN 연산자를 사용한다
- SELECT * FROM dept_emp IN ('d003','d004','d005') AND emp_no=10001;
- 이렇게하면 레인지스캔이아니라 하나씩 emp_no도 같이 인덱스 사용한다

11.3.3.1 NULL 값 비교 대체 (IFNULL,ISNULL)
- SELECT IF(emp_no IS NOT NULL, true, false) FROM dept_emp; -> ISNULL()
- 항상 위에처럼 사용했는데,,,함수로 존재했다니,,ㅜ
- IFNULL을 사용할때도 ISNULL() 작동하는 셀렉문을 통해서 조건을 통해 가져왔는데,,
- 앞으론 이렇게 써야지

11.3.3.3 날짜시간포맷
- 그냥 date타입은 string으로 검색하면 되나보다 정도만 알고있었는데 역시 내부적으로 타입을 변환해주는거구나

**11.3.3.8 grpup by 문자열 결합(group_concat)**
- 중복제거하고 특정 seperator기준으로 하나의 문자열로 다 들고온다
- 이거 너무 유용할것같다!
- 프로그래밍적으로 list로 들고오는걸 특정 seperator기준으로 조인해서 가져오는 것도 있으니 참고바람

11.3.3.13 sleep, 14 benchmark -> 개발용/성능테스트

11.3.3.15 IP주소변환
- Q) 왜 바이너리로 저장하는 예제가 나오지? -> 보안?

11.3.3.16~22
- JSON으로 이것저것 가능한가봄
- Q) 타입중에 JSON이 있었던가?
https://www.joinc.co.kr/w/man/12/mysql/json

11.4.1 select절의 처리 순서
- 쿼리절 처리순서에서 벗어나게 하려면 서브쿼리 LIMIT 활용
- 하지만 이렇게 인라인뷰가 사용되면 임시테이블이 사용되기 때문에 주의

**11.4.2.1 인덱스 사용하기 위한 기본 규칙**
- 인덱스는 값 그대로 B-TREE에 정렬해서 저장한다
- WHERE, GROUP BY, ORDER BY에서도 또한 값 그대로 정렬할때만 B-TREE 정렬된 인덱스 사용한다
- 가공후 다른 상숫값과 비교하면 인덱스 이용안된다
- **항상 값의 타입에 맞춰 select하도록 해라**
- Q) 근데 인공pk로 정렬된 row들에서 string으로 검색하면 더 빠르게 찾는거같았는데 그냥 느낌이 그랬던거겠지..?ㅋㅋ

11.4.3.3 날짜비교
- 요약: 인덱스사용하게 잘 변환해서 비교해라

**Comment by jihye-woo** [comment]
### 영문 대소문자 구분
- 유닉스 계열 + mysql 대소문자 구분 

### 예약어
- 테이블 생성할 때는 항상 역따옴표로 테이블이나 컬럼의 이름을 둘러싸지 않은 상태로 생성 권장
   -> 서버가 예약어 여부 알려줌

### MySQL 연산자와 내장 함수
- ANSI 표준 형태 연산자 사용 권장 (데이터베이스 변경될 때 )


**TINYINT**
 - 128 to 127
- https://www.tutorialspoint.com/mysql/mysql-data-types.htm#:~:text=TINYINT%20%E2%88%92%20A%20very%20small%20integer,of%20up%20to%204%20digits.

**비교 연산자**
- <=>  (=비교 + null 비교)

**REGEXP**
- 인덱스 레인지 스캔 사용할 수 없으므로, 최대한 데이터 조회 범위 줄일 것

**날짜와 시간의 연산**
- SYSDATE() : 현재 시각
- NOW() : 쿼리가 실행된 시각


### SELECT
- 각 쿼리 절의 실행 순서(54p)
    - [ 드라이빙과 드리븐 테이블 : 조인 + where 적용 ] -> GROUP BY -> DISTINCT -> HAVING -> ORDER BY -> LIMIT
    - limit 다음 order by 적용 원하면 인라인 뷰 사용 -> 임시테이블 사용되는 것 감안해야 함

- 인덱스로 저장된 데이터타입과 달라서 최적화 문제 발생할 수도
    - Where/ Group By / Order By 절에서 인덱스 사용하기 위해서는 인덱스된 칼럼 값 자체를 사용해야 함


**WHERE 절의 인덱스 사용**
- MySQL 이전 버전까지는 하나의 인덱스를 구성하는 각 칼럼의 정렬 순서가 혼합되어 사용 X
- 이제는 인덱스 칼럼 순서 != Where 조건절 컬럼 순서 이더라도 인덱스 사용 가능
- 단, WHERE 조건에 OR이 있으면 주의하자

**GROUP BY**
- 인덱스 칼럼 순서 == GROUP BY절 컬럼 순서

**WHERE + ORDER BY(혹은 GROUP BY)**
- WHERE + ORDER BY 둘다 같은 인덱스 : 중간에 빠지는 컬럼이 있으면 모두 인덱스 탈 수 없다
- WHERE절만 인덱스 사용
- ORDER BY 절만 인덱스 사용

**Comment by kyupid** [comment]
11.3.3.8 grpup by 문자열 결합(group_concat) 요거 너무 유용할거 같다고 생각했는데 진짜 쓰게 되었네요 ㅎㅎ 공부한 보람이 있습니다 ㅎㅎ
