### ISSUE TITLE
Ch12. 확장검색

### ISSUE THREAD

**Issue by kihyuk-sung** [BackendSquid/RealMySQL#28]
207p ~ 261p
11.8 쿼리 성능 테스트 ~ Ch12 확장검색

**Comment by jihye-woo** [comment]
207p ~ 228p 로 변경!
11.8 쿼리 성능 테스트 ~ 12.1 전문검색

**Comment by jihye-woo** [comment]
### 11.8 쿼리 성능 테스트
- 운영체제 캐시
   - InnoDB 스토리지 엔진은 사용 X (파일 시스템, 캐시 및 버퍼를 거치지 않고 다이렉트 IO 사용)
   - MyISAM 운영체제 캐시 사용 O (이에 대한 의존도 높다)
   - 결론, 운영체제 캐시가 쿼리 성능 테스트에 영향을 미칠 수도 있으니, 테스트 하기 전에 캐시 비워라
- InnoDB 스토리지 엔진이 관리하는 캐시 : 버퍼풀
   1) 인덱스 페이지
   2) 데이터 페이지
   3) 쓰기 작업을 위한 버퍼링 작업 처리
        - 4.2.7 InnoDB 버퍼풀 (더티페이지, 리두로그)
        - 4.2.8 Double Write Buffer (변경된 데이터 페이지를 모아서 한 번에 DoubleWrite 버퍼에 기록, 순차 IO에 유리, SSD에서는 오버헤드만 많을 수도)
    - 그럼 인덱스와 데이터 캐싱 시, 페이지 단위로 이루어지는건가
- MyISAM 스토리지 엔진이 관리하는 캐시 : 키캐시
   1) 인덱스 데이터에 대해서만 캐싱
### 12.1 전문 검색
- 형태소 분석 : 띄어쓰기 단위로 분리
- n-gram : 주어진 길이로 쪼개서 인덱싱
   - 검색어의 길이가 `ngram_token_size` 보다 크거나 같아야 검색 가능
- 전문 검색 쿼리 모드 : 자연어 VS 불리언
- 뜬금없지만 삭제와 관련된 SQL 키워드 세 가지
   - DELETE : 데이터만 삭제, 디스크 상의 공간은 남아있다
   - TRUNCATE : 최초 테이블이 만들어졌던 상태(컬럼 값만 존재)로 돌아감. 디스크 공간 X / 인덱스 X
   - DROP : 데이터, 테이블 모두 삭제. 디스크 공간 X / 인덱스 X / 제약조건 X
- 전문 검색 인덱스는 원래의 값을 그대로 인덱싱하지 않고 가공한다

### 마안약에 시간이 남는다면
- Read Committed VS Repeatable Read 어떤 트랜잭션 레벨 사용하고 있는지 (1장 176p)
   - Repeatable Read의 경우
      - next key lock 덕분에 팬텀 리드 발생 X
      - next key lock 때문에 데드락 발생 가능성 높다 ([링크](https://dev.mysql.com/doc/refman/8.0/en/innodb-transaction-isolation-levels.html)) 
   - 기본적으로 mysql 레코드 락 동작 방식 : 인덱스가 있으면, 인덱스에 락을 건다
      - select for update 수행을 위해서는 변경할 레코드를 찾기 위해 해당하는 인덱스에 락을 건다.
      - 만약 일부 조건에 대해서는 인덱스가 없다면 해당하는 레코드에 모두 락을 건다
      - 예시 171p 보면, first_name 인덱스 O, last_name 인덱스 X -> 253건의 레코드 모두 잠긴다
      - Tx1 이 이런 상황이고, 다른 Tx2이 락걸린 데이터를 업데이트하고 싶어함 ...-> 다른 조건들이 얽혀서 데드락 발생 가능
- Q. `@Transactional`에서도 트랜잭션 격리 레벨 설정 가능한데, DB 단의 트랜잭션 레벨과 어떤 관계?
     -  DB 트랜잭션 레벨과 관계없이 어플리케이션 단에서 추상화해서 마치 `@Transactional`에서 정의한 트랜잭션 레벨로 동작하는 것 처럼 보이게끔 동작시켜주는건가.. hoxy 아시는 분.. 설명 감사드립니다🙏 (사실 제가 여기에 대해서 많이 공부하지 않고 냅다 질문부터 쓴겁니다 허허)
     - TMI, `@Transactional`의 기본설정은 연결된 DB의 트랜잭션 격리레벨로 따라간다고 함
     - 제인 공유 링크 : https://stackoverflow.com/questions/45627433/precedence-of-spring-transaction-isolation-level-vs-database-isolation-level

**Comment by janeljs** [comment]
## 11.8 쿼리 성능 테스트
- InnoDB 버퍼풀이 MySQL 서버 종료 시 자동으로 덤프됐다가 적재된다고 하는데 왜 off 후 재시작 해줘야 한다고 하는가? (p.208~209)
>  The ability to restore the buffer pool at startup shortens the warmup period by reloading disk pages that were in the buffer pool before the restart rather than waiting for DML operations to access corresponding rows.
출처: https://dev.mysql.com/doc/refman/8.0/en/innodb-preload-buffer-pool.html
  - self 답변: 쿼리 성능에 영향 최소화하려고 버퍼나 캐시 최소화하는 방법 알아보는 중이었음
## 12.1 전문 검색
- 기본 stopword 사용할 때 주의할 점
  - https://gywn.net/2017/04/mysql_57-ngram-ft-se/
 - search modifier
   - https://dev.mysql.com/doc/refman/8.0/en/fulltext-search.html
   - https://gngsn.tistory.com/162
- mysql fts vs es
  - https://stackoverflow.com/questions/41892179/elastic-search-full-text-vs-mysql-full-text
  - https://www.reddit.com/r/devops/comments/av704k/mysql_full_text_search_versus_elasticsearch/
  - https://scoutapm.com/blog/from-mysql-full-text-search-to-elasticsearch

**Comment by kihyuk-sung** [comment]
# 11.8 쿼리 성능 테스트
## 쿼리의 성능에 영향을 미치는 요소
1. OS 캐시
- InnoDB는 일반적으로 Direct I/O
- MyISAM은 OS 캐시 사용
2. MySQL 서버의 버퍼 풀
- InnoDB 버퍼 풀 (페이지 캐싱, 쓰기 버퍼링)
- MyISAM 키 캐시 (인덱스)
3. MySQL 서버의 독립 여부
- File IO, 스케쥴링, 네트워크 등 MySQL 자체가 독립적으로 동작하는지, 다른 App 과 동시에 실행되는지 등에 따라 성능 영향이 존재
4. 쿼리 테스트 횟수
- 버퍼풀 등에 의해 캐시가 준비된 상태 (워밍업 상태)
- 캐시가 없는 상태 (콜드 상태)
- 쿼리를 번갈아가면서 여러번 실행하여 테스트 해본다.
5. 기타 (Application Level)
- 네트워크
- 커넥션 풀의 크기가 적당한지
# 12 확장 검색
## 전문 검색
- 형태소 검색 
  - 서구권 언어의 경우 어근 분석
  - 한국어의 경우 생각보다 유용하지 않음
- n-gram 파서
  - 문장을 n개의 단어로 분리하여 저장
## n-gram 파서
- 검색 단어가 n보다 작을 경우, 결과 없음
- n보다 큰 경우 검색 가능
- 자연어 검색
- 불리언 검색
  - 특정 단어는 존재하고, 특정 단어는 존재하지 않는 경우 검색
  - 스코어 계산 법이 자연어와 다름
- 검색어 확장
  - 해당 검색어로 먼저 검색한 후, 관련 단어를 모아서 다시 검색
- 전문 검색 인덱스 디버깅
  - information_schema.innodb_ft_config
  - information_shcema.innodb_ft_index_table
    - 인덱스 엔트리 목록
  - information_schema.innodb_ft_index_cache
    - 인덱스를 임시로 가지고 있는 캐시
  - information_schema.innodb_ft_deleted / innodb_ft_being_deleted
    - 삭제된 / 삭제 중인 인덱스
